### PR TITLE
Commands need to be able to execute, regardless of their subjects bei…

### PR DESCRIPTION
**Pull request by 4c0n**
In order to solve bug 352633 (https://bugs.kde.org/show_bug.cgi?id=352633) I'd like to suggest the following change to CmdBaseObjectCommand.

### CODE REVIEW

**Comment by 4c0n** [comment]
@rhabacker I've updated the code to use a QPointer and restored the original behaviour (looking up the object in the document first). I know the pull request is directed at the master branch, but would love to see the final fix end up in version 15.04, do you think that is possible at all?

**Comment by rhabacker** [comment]
You are refering to 15.12, not 15.04 ? 15.12 is the current stable branch.

**Comment by rhabacker** [comment]
Please merge all new commits on this branch into one with a descriptive commit message and the following tags (until Dec 2 2015 to get this into 15.11.90 [1])

BUG: 352633
FIXED-IN: 2.17.90 (KDE Applications 15.11.90)

which can be cherry-picked then into Applications/15.12 branch of kde umbrello repo.

[1] https://techbase.kde.org/Schedules/Applications/15.12_Release_Schedule#Wednesday.2C_December_2.2C_2015:_KDE_Applications_15.12_RC_.2815.11.90.29_Tagging_and_Release

**Comment by 4c0n** [comment]
Alright done, so merging to the master branch is ok? Or do I need to open a new pull request to another branch?

**Comment by 4c0n** [comment]
Commit has been cherry picked at the KDE. Bug report is closed.
Closing pull request.

**Pull request closed without merging**
